version: '3.4'
services:
    web:
        build: .
        container_name: django_app1
        command: gunicorn djangopj.wsgi:application -w 2 -b :8000
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
        restart: always
        volumes:
            - ./djangopj:/var/www/djangopj

    postgres:
        container_name: postgres1
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        volumes:
# This data source path should be changed based on env
            - ./_data/docker/psql:/var/lib/postgresql
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./backups/postgresql:/backup
        environment:
            - POSTGRES_PASSWORD=dockerPsqlPassword
            - POSTGRES_USER=postgres

    nginx:
        container_name: nginx1
        image: nginx:alpine
        links:
            - web:web
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./djangopj:/var/www/djangopj
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./_log/nginx:/var/log/nginx
